[project]
name = "soreq"
version = "0.1.0"
description = "A Python package for Soreq, a tool for managing and analyzing data."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
]
